version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pharmacy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pharmacy_db
    ports:
      - '5432:5432'
    volumes:
      - ./Back_end/CSDL/pharmacy_db_v2.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pharmacy_data:/var/lib/postgresql/data
    networks:
      - pharmacy_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pharmacy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pharmacy.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - '5050:80'
    networks:
      - pharmacy_net
    depends_on:
      - db
    volumes:
    
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ./Back_end
    container_name: pharmacy_backend
    env_file:
      - ./Back_end/.env
    environment:
      DB_USER: postgres
      DB_PASS: 123456
      DB_NAME: pharmacy_db
      DB_HOST: db
      DB_PORT: 5432
      PORT: 5001
      PGCLIENTENCODING: UTF8
    depends_on:
      - db
    ports:
      - '5001:5001'
    volumes:
      - ./Back_end:/app
    networks:
      - pharmacy_net

  frontend:
    build: ./Front_end
    container_name: pharmacy_frontend
    environment:
      - VITE_API_BASE=http://localhost:5001/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    ports:
      - '5173:5173'
    volumes:
      - ./Front_end:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - pharmacy_net

volumes:
  pharmacy_data:  
  frontend_node_modules:
  
  pgadmin_data:

networks:
  pharmacy_net:
    driver: bridge
